In [1]:
import numpy as np
import pandas as pd
import scipy
import scipy.stats

In [2]:
df = pd.read_csv('bicicletas-compartidas.csv')
df.columns

Index(['fecha', 'bicis-compartidas', 'temp-obs', 'sens-temp', 'hum', 'viento',
       'codigo-clima', 'festivo', 'findesemana', 'cuartil-ano'],
      dtype='object')

In [3]:
y = df['bicis-compartidas'].values
y

array([182, 138, 134, ..., 337, 224, 139])

In [4]:
# Limpiamos el arreglo de ceros
y = np.where(y == 0, 1, y)

In [5]:
# Obtenemos  el valor minimo
np.min(y)

1

In [6]:
#obtenemos el valor maximo
np.max(y)

7860

In [7]:
# Promedio (medida de tendencia central mas importante)
np.mean(y)

1143.1016997817849

In [8]:
np.sum(y)/len(y)

1143.1016997817849

In [9]:
# Calculo media armonica
scipy.stats.mstats.hmean(y)

241.65180305136826

In [10]:
# media
np.median(y)

844.0

In [11]:
# moda: el valor de y con la maxima frecuencia 
moda = np.nan
moda

nan

In [12]:
valores, conteo_valores = np.unique(y, return_counts=True)

In [13]:
valores

array([   1,    9,   10, ..., 7208, 7531, 7860])

In [14]:
conteo_valores

array([1, 1, 1, ..., 1, 1, 1])

In [15]:
#Encontramos el indice del valor maximo del array conte_valores
posicion = np.argmax(conteo_valores)
posicion

38

In [16]:
#El valor de mayor frecuencia
moda = valores[posicion]
moda

46

In [17]:
# Desviacion estandar, que tanto se alejan los valorx xi de su valor promedio
np.std(y)

1085.0768508213835

##### Revisiones

In [18]:
y_alterado = y.copy()

#agregamos un  valor extremo
y_alterado[ y_alterado == max(y_alterado)] = 10000000

In [19]:
print(np.mean(y))
print(np.mean(y_alterado))

1143.1016997817849
1716.9009417709888


In [20]:
print(np.median(y))
print(np.median(y_alterado))

844.0
844.0


**Conclusiones:** La media y desviacion estandar son suceptibles a valores extremos, se debe tener cuidado al aplicarlas